// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mepuzpkxfjszfexittbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lcHV6cGt4ZmpzemZleGl0dGJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwMDM5MDksImV4cCI6MjA4NjU3OTkwOX0.x12J9_4RdLCMHDPw6et9wPb3kx9FLH3eK_XoFTxI7rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});